from pathlib import Path
import subprocess
import tempfile
import unittest

from check_repository import scan


class RepositoryCheckTests(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.root = Path(self.directory.name)
        self.git("init", "-q")
        self.git("-c", "user.name=Test", "-c", "user.email=test@example.invalid",
                 "commit", "--allow-empty", "-qm", "initial")

    def git(self, *args):
        return subprocess.check_output(["git", "-C", str(self.root), *args], stderr=subprocess.PIPE)

    def write(self, name, value):
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(value)

    def test_untracked_private_file_is_rejected_and_ignored_file_is_excluded(self):
        self.write("test.sqlite", "private")
        self.assertTrue(scan(self.root)[0])
        self.write(".gitignore", "*.sqlite\n")
        self.assertEqual(scan(self.root)[0], [])
        self.git("add", "-f", "test.sqlite")
        self.assertTrue(scan(self.root)[0], "Ignoring a file must not hide an already tracked database")

    def test_credential_is_redacted_and_plain_product_text_passes(self):
        self.write("README.md", "Read the map and explore a neighborhood.\n")
        self.assertEqual(scan(self.root)[0], [])
        secret = "gh" + "p_" + "a" * 36
        self.write("settings.txt", secret)
        issues = scan(self.root)[0]
        self.assertEqual(len(issues), 1)
        self.assertNotIn(secret, issues[0])

    def test_attribution_in_candidate_file_and_commit_is_rejected(self):
        wording = "Generated by " + "Clau" + "de"
        self.write("README.md", wording)
        self.assertTrue(scan(self.root)[0])
        self.git("add", "README.md")
        self.git("-c", "user.name=Test", "-c", "user.email=test@example.invalid",
                 "commit", "-qm", wording)
        self.write("README.md", "Product documentation")
        self.assertTrue(any(issue.startswith("commit ") for issue in scan(self.root)[0]))

    def test_symlink_is_not_followed(self):
        (self.root / "external").symlink_to("/does/not/exist")
        self.assertTrue(any("symlink" in issue for issue in scan(self.root)[0]))


if __name__ == "__main__":
    unittest.main()
